name: Deploy to FTP

on:
  push:
    branches:
      - feat/cd/8-github-action-ftp-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Prepare deploy directory (git archive)
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          mkdir -p deploy
          git archive --format=tar HEAD | tar -x -C deploy

      - name: Ensure docker home writable
        run: |
          mkdir -p "$RUNNER_TEMP/_github_home"
          chmod -R 0777 "$RUNNER_TEMP/_github_home"

      - name: Deploy to FTP/FTPS
        uses: airvzxf/ftp-deployment-action@v2
        env:
          HOME: /github/workspace
        with:
          server: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./deploy"
          remote_dir: "/"
          ssl_verify_certificate: "false"