# Deploy to FTP/FTPS using SamKirkland/FTP-Deploy-Action
name: Deploy to FTP

on:
  push:
    branches:
      - feat/cd/8-github-action-ftp-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Clean deploy directory
        run: 
          rm -rf .git
          rm -rf .github
          rm -rf node_modules
          rm -rf quality
          rm -f package.json package-lock.json

      - name: Deploy to FTP/FTPS
        uses: airvzxf/ftp-deployment-action@v2
        with:
          server: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./"
          remote_dir: "/"
          ssl_verify_certificate: "false"